baseURL = 'https://tsadikstudios.github.io/'
languageCode = 'en-us'
title = 'Tsadik Studios'
theme = 'PaperMod'

[params]
  env = 'production'
  description = 'The intersection of rigorous manual labor, creative technology, and analytical depth.'
  author = 'Tsadik Studios'
  defaultTheme = 'auto'
  ShowReadingTime = true
  ShowShareButtons = false

[menu]
  [[menu.main]]
    identifier = "visuals"
    name = "Visuals"
    url = "/visuals/"
    weight = 10
  [[menu.main]]
    identifier = "audio"
    name = "Audio"
    url = "/audio/"
    weight = 20
  [[menu.main]]
    identifier = "literature"
    name = "Literature"
    url = "/literature/"
    weight = 30
