[menu]
  [[menu.main]]
    identifier = "art-shop"
    name = "Art Shop"
    url = "/art-shop/"
    weight = 10
  [[menu.main]]
    identifier = "audio"
    name = "Audio"
    url = "/audio/"
    weight = 20
  [[menu.main]]
    identifier = "literature"
    name = "Literature"
    url = "/literature/"
    weight = 30